services:
  - type: web
    name: flask-jekyll-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn manage:app
    envVars:
      - key: FLASK_CONFIG
        value: default
